<?php
/**
 * Linna App.
 *
 * This file is automatically generated, do not modify.
 *
 * @author Sebastian Rapetti <sebastian.rapetti@alice.it>
 * @copyright (c) 2018, Sebastian Rapetti
 * @license http://opensource.org/licenses/MIT MIT License
 */
declare(strict_types=1);

return array(
  0 =>
  array(
    'name' => 'Home',
    'method' => 'GET',
    'url' => '/',
    'model' => 'App\\Models\\HomeModel',
    'view' => 'App\\Views\\HomeView',
    'controller' => 'App\\Controllers\\HomeController',
    'action' => '',
    'default' => false,
    'param' =>
    array(
    ),
    'callback' => false,
  ),
  1 =>
  array(
    'name' => 'E404',
    'method' => 'GET',
    'url' => '/error',
    'model' => 'App\\Models\\NullModel',
    'view' => 'App\\Views\\E404View',
    'controller' => 'App\\Controllers\\E404Controller',
    'action' => '',
    'default' => false,
    'param' =>
    array(
    ),
    'callback' => false,
  ),
);
